### ISSUE TITLE
Bug: Initial load fails

### ISSUE THREAD

**Issue by tseijp** [tseijp/plre#7]
**Describe the bug**
load fails and webrtc connection does not complete when page is opened for the first time.

**To Reproduce**
1. open plre site as secret page

**Expected behavior**
1. display ploted object

**Screenshots**
![screenshot-plre tsei jp-2023 10 22-18_39_21](https://github.com/tseijp/plre/assets/40712342/d44b46e8-cfce-4047-96c4-cfdd2019cfdd)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**

<details>
<summary>Log</summary>

```ruby
Uncaught TypeError: Cannot destructure property 'EditorState' of 'i.libs' as it is undefined.
    at Function.<anonymous> (1df93b7f.20ae8614.js:1:21865)
    at 1df93b7f.20ae8614.js:1:82869
    at 537.a1f928e6.js:1:79172
    at Set.forEach (<anonymous>)
    at t.has.e.<computed> [as changeActive] (537.a1f928e6.js:1:79142)
    at Function.<anonymous> (1df93b7f.20ae8614.js:1:71953)
    at 1df93b7f.20ae8614.js:1:82869
    at 537.a1f928e6.js:1:79172
    at Set.forEach (<anonymous>)
    at t.has.e.<computed> [as connected] (537.a1f928e6.js:1:79142)

WebSocket connection to 'wss://y-webrtc-eu.fly.dev/' failed: 
```

**Comment by tseijp** [comment]
Perhaps changeActive is started before codemirror dynamic import completes.

https://github.com/tseijp/plre/blob/0ef920745aa0778e0b9e32ae366e723c9643b6e1/examples/docs/ui/organisms/hooks/useCodemirror.ts#L92-L99

https://github.com/tseijp/plre/blob/0ef920745aa0778e0b9e32ae366e723c9643b6e1/examples/docs/ui/templates/hooks/useInitStorage.ts#L166-L180
